/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models

import id.my.rizalanggoro.arta.openapi.models.DtoCategory

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param currentBalance 
 * @param latestCategories 
 * @param totalExpense 
 * @param totalIncome 
 */
@Serializable

data class CashDashboardRes (

    @SerialName(value = "current_balance")
    val currentBalance: kotlin.Double,

    @SerialName(value = "latest_categories")
    val latestCategories: kotlin.collections.List<DtoCategory>,

    @SerialName(value = "total_expense")
    val totalExpense: kotlin.Double,

    @SerialName(value = "total_income")
    val totalIncome: kotlin.Double

) {


}

