/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param currentBalance 
 * @param todayExpense 
 * @param todayIncome 
 */
@Serializable

data class CashDashboardResFinancialSummary (

    @Contextual @SerialName(value = "current_balance")
    val currentBalance: java.math.BigDecimal,

    @Contextual @SerialName(value = "today_expense")
    val todayExpense: java.math.BigDecimal,

    @Contextual @SerialName(value = "today_income")
    val todayIncome: java.math.BigDecimal

) {


}

