/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models

import id.my.rizalanggoro.arta.openapi.models.CashDashboardResFinancialSummary
import id.my.rizalanggoro.arta.openapi.models.CashDashboardResRecentTransactionsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param activeWalletName 
 * @param financialSummary 
 * @param recentTransactions 
 */
@Serializable

data class CashDashboardRes (

    @SerialName(value = "active_wallet_name")
    val activeWalletName: kotlin.String,

    @SerialName(value = "financial_summary")
    val financialSummary: CashDashboardResFinancialSummary,

    @SerialName(value = "recent_transactions")
    val recentTransactions: kotlin.collections.List<CashDashboardResRecentTransactionsInner>

) {


}

