/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param name 
 * @param type income, expense
 * @param updatedAt 
 * @param userId nil for default categories
 */
@Serializable

data class DomainCategory (

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* income, expense */
    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String? = null,

    /* nil for default categories */
    @SerialName(value = "user_id")
    val userId: kotlin.Int? = null

) {


}

