/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param carat 
 * @param createdAt 
 * @param date 
 * @param grams 
 * @param id 
 * @param notes 
 * @param price price per gram in IDR
 * @param type pure_gold or jewelry
 * @param updatedAt 
 * @param walletId 
 */
@Serializable

data class DomainGold (

    @SerialName(value = "carat")
    val carat: kotlin.Double,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "date")
    val date: kotlin.String,

    @SerialName(value = "grams")
    val grams: kotlin.Double,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "notes")
    val notes: kotlin.String,

    /* price per gram in IDR */
    @SerialName(value = "price")
    val price: kotlin.Double,

    /* pure_gold or jewelry */
    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @SerialName(value = "wallet_id")
    val walletId: kotlin.Int

) {


}

