/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param currency 
 * @param currencySymbol 
 * @param exchangeRate 
 * @param id 
 * @param pricePerOunceUsd 
 * @param sourceReadableAge 
 * @param sourceUpdatedAt 
 * @param symbol 
 */
@Serializable

data class DomainGoldPrice (

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "currency_symbol")
    val currencySymbol: kotlin.String,

    @Contextual @SerialName(value = "exchange_rate")
    val exchangeRate: java.math.BigDecimal,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "price_per_ounce_usd")
    val pricePerOunceUsd: kotlin.Double,

    @SerialName(value = "source_readable_age")
    val sourceReadableAge: kotlin.String,

    @SerialName(value = "source_updated_at")
    val sourceUpdatedAt: kotlin.String,

    @SerialName(value = "symbol")
    val symbol: kotlin.String

) {


}

