/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amount 
 * @param categoryId 
 * @param createdAt 
 * @param date 
 * @param description 
 * @param id 
 * @param updatedAt 
 * @param walletId 
 */
@Serializable

data class DomainTransaction (

    @SerialName(value = "amount")
    val amount: kotlin.Double,

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "date")
    val date: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @SerialName(value = "wallet_id")
    val walletId: kotlin.Int

) {


}

