/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param carat 
 * @param createdAt 
 * @param id 
 * @param taxRate 
 * @param updatedAt 
 * @param userId 
 */
@Serializable

data class DomainGoldTaxPreference (

    @Contextual @SerialName(value = "carat")
    val carat: java.math.BigDecimal,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @Contextual @SerialName(value = "tax_rate")
    val taxRate: java.math.BigDecimal,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @SerialName(value = "user_id")
    val userId: kotlin.Int

) {


}

