/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models

import id.my.rizalanggoro.arta.openapi.models.DomainFxRate
import id.my.rizalanggoro.arta.openapi.models.DomainGoldPrice
import id.my.rizalanggoro.arta.openapi.models.DomainGoldTaxPreference
import id.my.rizalanggoro.arta.openapi.models.DtoGold

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fxRate 
 * @param goldPrice 
 * @param goldPricePerGramIdr 
 * @param latestGolds 
 * @param profit 
 * @param taxPreferences 
 * @param totalAsset 
 * @param totalBuyPrice 
 * @param totalGoldItems 
 * @param totalWeight 
 */
@Serializable

data class DtoGoldDashboard (

    @SerialName(value = "fx_rate")
    val fxRate: DomainFxRate,

    @SerialName(value = "gold_price")
    val goldPrice: DomainGoldPrice,

    @SerialName(value = "gold_price_per_gram_idr")
    val goldPricePerGramIdr: kotlin.Double,

    @SerialName(value = "latest_golds")
    val latestGolds: kotlin.collections.List<DtoGold>,

    @SerialName(value = "profit")
    val profit: kotlin.Double,

    @SerialName(value = "tax_preferences")
    val taxPreferences: kotlin.collections.List<DomainGoldTaxPreference>,

    @SerialName(value = "total_asset")
    val totalAsset: kotlin.Double,

    @SerialName(value = "total_buy_price")
    val totalBuyPrice: kotlin.Double,

    @SerialName(value = "total_gold_items")
    val totalGoldItems: kotlin.Int,

    @SerialName(value = "total_weight")
    val totalWeight: kotlin.Double

) {


}

