/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models

import id.my.rizalanggoro.arta.openapi.models.DomainCategory
import id.my.rizalanggoro.arta.openapi.models.DomainTransaction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` 
 * @param totalAmount 
 * @param transactionCount 
 * @param transactions 
 */
@Serializable

data class GetCategoryRes (

    @SerialName(value = "data")
    val `data`: DomainCategory,

    @SerialName(value = "total_amount")
    val totalAmount: kotlin.Double,

    @SerialName(value = "transaction_count")
    val transactionCount: kotlin.Int,

    @SerialName(value = "transactions")
    val transactions: kotlin.collections.List<DomainTransaction>

) {


}

