/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param carat 
 * @param date 
 * @param grams 
 * @param notes 
 * @param price 
 * @param type 
 * @param walletId 
 */
@Serializable

data class GoldCreateGoldReq (

    @SerialName(value = "carat")
    val carat: kotlin.Double,

    @SerialName(value = "date")
    val date: kotlin.String,

    @SerialName(value = "grams")
    val grams: kotlin.Double,

    @SerialName(value = "notes")
    val notes: kotlin.String,

    @SerialName(value = "price")
    val price: kotlin.Double,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "wallet_id")
    val walletId: kotlin.Int

) {


}

