/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package id.my.rizalanggoro.arta.openapi.models

import id.my.rizalanggoro.arta.openapi.models.DtoGold

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param activeWalletName 
 * @param buyPrice 
 * @param latestDollarPrice 
 * @param latestGoldPricePerGramIdr 
 * @param profit 
 * @param recentGolds 
 * @param totalAsset 
 * @param totalGoldItems 
 * @param totalWeight 
 */
@Serializable

data class GoldDashboardRes (

    @SerialName(value = "active_wallet_name")
    val activeWalletName: kotlin.String? = null,

    @Contextual @SerialName(value = "buy_price")
    val buyPrice: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "latest_dollar_price")
    val latestDollarPrice: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "latest_gold_price_per_gram_idr")
    val latestGoldPricePerGramIdr: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "profit")
    val profit: java.math.BigDecimal? = null,

    @SerialName(value = "recent_golds")
    val recentGolds: kotlin.collections.List<DtoGold>? = null,

    @Contextual @SerialName(value = "total_asset")
    val totalAsset: java.math.BigDecimal? = null,

    @SerialName(value = "total_gold_items")
    val totalGoldItems: kotlin.Int? = null,

    @Contextual @SerialName(value = "total_weight")
    val totalWeight: java.math.BigDecimal? = null

) {


}

