// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | 'https://localhost:8080/' | (string & {});
};

export type CashDashboardRes = {
    current_balance: number;
    latest_categories: Array<DtoCategory>;
    prev_period_expense: number;
    prev_period_income: number;
    total_expense: number;
    total_income: number;
};

export type CreateCategoryRes = {
    data: DomainCategory;
    total_amount?: number;
    transaction_count?: number;
    transactions?: Array<DomainTransaction>;
};

export type CreateGoldRes = {
    data: DomainGold;
    profit: number;
    sell_price: number;
};

export type CreateGoldTaxPreferenceRes = {
    preference: DtoGoldTaxPreference;
};

export type CreateReleaseReq = {
    url: string;
    version_code: number;
};

export type CreateTransactionReq = {
    amount: number;
    category_id: number;
    date: string;
    description: string;
    wallet_id: number;
};

export type CreateTransactionRes = {
    category?: DomainCategory;
    data: DomainTransaction;
};

export type CreateWalletRes = {
    data: DomainWallet;
};

export type DeleteCategoryRes = {
    message: string;
};

export type DeleteGoldRes = {
    message: string;
};

export type DeleteGoldTaxPreferenceRes = {
    message: string;
};

export type DeleteTransactionRes = {
    message: string;
};

export type DeleteWalletRes = {
    message: string;
};

export type GetGoldRes = {
    data: DomainGold;
    profit: number;
    sell_price: number;
};

export type GetTransactionRes = {
    category?: DomainCategory;
    data: DomainTransaction;
};

export type GetWalletRes = {
    data: DomainWallet;
};

export type GoldDashboardRes = {
    data: DtoGoldDashboard;
};

export type ListGoldTaxPreferencesRes = {
    preferences: Array<DtoGoldTaxPreference>;
};

export type LoginReq = {
    email: string;
    password: string;
};

export type LoginRes = {
    email: string;
    name: string;
    token: string;
    user_id: string;
};

export type LogoutRes = {
    message: string;
};

export type MeRes = {
    data: DomainUser;
    updated_at: string;
};

export type PriceHistoryRes = {
    data: Array<DtoPricePoint>;
};

export type RegisterReq = {
    email: string;
    name: string;
    password: string;
};

export type RegisterRes = {
    email: string;
    name: string;
    token: string;
    user_id: string;
};

export type ReleaseRes = {
    data: DomainRelease;
};

export type UpdateCategoryRes = {
    data: DomainCategory;
    total_amount?: number;
    transaction_count?: number;
    transactions?: Array<DomainTransaction>;
};

export type UpdateGoldRes = {
    data: DomainGold;
    profit: number;
    sell_price: number;
};

export type UpdateGoldTaxPreferenceRes = {
    preference: DtoGoldTaxPreference;
};

export type UpdateTransactionReq = {
    amount: number;
    category_id: number;
    date: string;
    description: string;
    wallet_id: number;
};

export type UpdateTransactionRes = {
    category?: DomainCategory;
    data: DomainTransaction;
};

export type UpdateWalletRes = {
    data: DomainWallet;
};

export type CategoryCreateCategoryReq = {
    name: string;
    type: string;
};

export type CategoryListCategoriesRes = {
    categories: Array<DtoCategory>;
};

export type CategoryUpdateCategoryReq = {
    name?: string;
    type?: string;
};

export type DomainCategory = {
    created_at: string;
    id: number;
    name: string;
    /**
     * income, expense
     */
    type: string;
    updated_at: string;
    /**
     * nil for default categories
     */
    user_id?: number;
};

export type DomainFxRate = {
    base: string;
    created_at: string;
    date: string;
    id: number;
    rate: number;
};

export type DomainGold = {
    carat: number;
    created_at: string;
    date: string;
    grams: number;
    id: number;
    notes: string;
    /**
     * price per gram in IDR
     */
    price: number;
    /**
     * pure_gold or jewelry
     */
    type: string;
    updated_at: string;
    wallet_id: number;
};

export type DomainGoldPrice = {
    created_at: string;
    currency: string;
    currency_symbol: string;
    exchange_rate: number;
    id: number;
    price_per_ounce_usd: number;
    source_readable_age: string;
    source_updated_at: string;
    symbol: string;
};

export type DomainGoldTaxPreference = {
    carat: number;
    created_at: string;
    id: number;
    tax_rate: number;
    updated_at: string;
    user_id: number;
};

export type DomainRelease = {
    created_at: string;
    id: number;
    updated_at: string;
    url: string;
    version_code: number;
};

export type DomainTransaction = {
    amount: number;
    category_id: number;
    created_at: string;
    date: string;
    description: string;
    id: number;
    updated_at: string;
    wallet_id: number;
};

export type DomainUser = {
    created_at: string;
    email: string;
    id: number;
    name: string;
    updated_at: string;
    wallets?: Array<DomainWallet>;
};

export type DomainWallet = {
    created_at: string;
    id: number;
    name: string;
    type: string;
    updated_at: string;
    user_id: number;
};

export type DtoCategory = {
    data: DomainCategory;
    total_amount?: number;
    transaction_count?: number;
    transactions?: Array<DomainTransaction>;
};

export type DtoError = {
    code: number;
    message: string;
};

export type DtoGold = {
    data: DomainGold;
    profit: number;
    sell_price: number;
};

export type DtoGoldDashboard = {
    fx_rate: DomainFxRate;
    gold_price: DomainGoldPrice;
    gold_taxes: Array<DtoGoldTax>;
    latest_golds: Array<DtoGold>;
    profit: number;
    retail_price: number;
    total_asset: number;
    total_buy_price: number;
    total_gold_items: number;
    total_weight: number;
};

export type DtoGoldTax = {
    data: DomainGoldTaxPreference;
    sell_price: number;
};

export type DtoGoldTaxPreference = {
    carat: number;
    created_at: string;
    id: number;
    tax_rate: number;
    updated_at: string;
    user_id: number;
};

export type DtoPricePoint = {
    timestamp: string;
    value: number;
};

export type DtoTransaction = {
    category?: DomainCategory;
    data: DomainTransaction;
};

export type DtoWallet = {
    data: DomainWallet;
};

export type GoldCreateGoldReq = {
    carat: number;
    date: string;
    grams: number;
    notes: string;
    price: number;
    type: string;
    wallet_id: number;
};

export type GoldGoldTaxPreferenceReq = {
    carat: number;
    tax_rate: number;
};

export type GoldListGoldsRes = {
    golds: Array<DtoGold>;
};

export type GoldUpdateGoldReq = {
    carat?: number;
    date?: string;
    grams?: number;
    notes?: string;
    price?: number;
    type?: string;
};

export type HealthHealthRes = {
    app_version: string;
    app_version_code: number;
    status: string;
};

export type WalletCreateWalletReq = {
    name: string;
    type: string;
};

export type WalletListWalletsRes = {
    wallets: Array<DtoWallet>;
};

export type WalletUpdateWalletReq = {
    name: string;
    type: string;
};

export type PostApiAuthLoginData = {
    /**
     * body
     */
    body: LoginReq;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginRes;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type LogoutData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * OK
     */
    200: LogoutRes;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetApiAuthMeData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetApiAuthMeErrors = {
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetApiAuthMeError = GetApiAuthMeErrors[keyof GetApiAuthMeErrors];

export type GetApiAuthMeResponses = {
    /**
     * OK
     */
    200: MeRes;
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type PostApiAuthRegisterData = {
    /**
     * body
     */
    body: RegisterReq;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Conflict
     */
    409: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
    /**
     * Created
     */
    201: RegisterRes;
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type ListCategoriesData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: {
        /**
         * income or expense
         */
        type?: string;
        /**
         * wallet_id
         */
        wallet_id?: number;
        /**
         * include transaction stats
         */
        include_stats?: boolean;
        /**
         * start_date (2006-01-02)
         */
        start_date?: string;
        /**
         * end_date (2006-01-02)
         */
        end_date?: string;
    };
    url: '/api/category';
};

export type ListCategoriesResponses = {
    /**
     * OK
     */
    200: CategoryListCategoriesRes;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    /**
     * body
     */
    body: CategoryCreateCategoryReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/category';
};

export type CreateCategoryResponses = {
    /**
     * Created
     */
    201: CreateCategoryRes;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type GetCategoryData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * category id
         */
        category_id: number;
    };
    query?: {
        /**
         * wallet_id
         */
        wallet_id?: number;
        /**
         * include_total_amount
         */
        include_total_amount?: boolean;
        /**
         * include_transactions
         */
        include_transactions?: boolean;
        /**
         * start_date
         */
        start_date?: string;
        /**
         * end_date
         */
        end_date?: string;
    };
    url: '/api/category/{category_id}';
};

export type GetCategoryResponses = {
    /**
     * OK
     */
    200: DtoCategory;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * category id
         */
        id: number;
    };
    query?: never;
    url: '/api/category/{id}';
};

export type DeleteCategoryResponses = {
    /**
     * OK
     */
    200: DeleteCategoryRes;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateCategoryData = {
    /**
     * body
     */
    body: CategoryUpdateCategoryReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * category id
         */
        id: number;
    };
    query?: never;
    url: '/api/category/{id}';
};

export type UpdateCategoryResponses = {
    /**
     * OK
     */
    200: UpdateCategoryRes;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetCashDashboardData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query: {
        /**
         * wallet_id
         */
        wallet_id: number;
        /**
         * start_date
         */
        start_date: string;
        /**
         * end_date
         */
        end_date: string;
    };
    url: '/api/dashboard/cash';
};

export type GetCashDashboardErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetCashDashboardError = GetCashDashboardErrors[keyof GetCashDashboardErrors];

export type GetCashDashboardResponses = {
    /**
     * OK
     */
    200: CashDashboardRes;
};

export type GetCashDashboardResponse = GetCashDashboardResponses[keyof GetCashDashboardResponses];

export type GetGoldDashboardData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query: {
        /**
         * wallet_id
         */
        wallet_id: number;
    };
    url: '/api/dashboard/gold';
};

export type GetGoldDashboardErrors = {
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetGoldDashboardError = GetGoldDashboardErrors[keyof GetGoldDashboardErrors];

export type GetGoldDashboardResponses = {
    /**
     * OK
     */
    200: GoldDashboardRes;
};

export type GetGoldDashboardResponse = GetGoldDashboardResponses[keyof GetGoldDashboardResponses];

export type GetPriceHistoryData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query: {
        /**
         * price type: gold or fx
         */
        type: string;
        /**
         * number of days of history (default 7)
         */
        days?: number;
    };
    url: '/api/dashboard/price-history';
};

export type GetPriceHistoryErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetPriceHistoryError = GetPriceHistoryErrors[keyof GetPriceHistoryErrors];

export type GetPriceHistoryResponses = {
    /**
     * OK
     */
    200: PriceHistoryRes;
};

export type GetPriceHistoryResponse = GetPriceHistoryResponses[keyof GetPriceHistoryResponses];

export type ListGoldsData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/gold';
};

export type ListGoldsResponses = {
    /**
     * OK
     */
    200: GoldListGoldsRes;
};

export type ListGoldsResponse = ListGoldsResponses[keyof ListGoldsResponses];

export type CreateGoldData = {
    /**
     * body
     */
    body: GoldCreateGoldReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/gold';
};

export type CreateGoldResponses = {
    /**
     * Created
     */
    201: CreateGoldRes;
};

export type CreateGoldResponse = CreateGoldResponses[keyof CreateGoldResponses];

export type ListGoldTaxPreferencesData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/gold/tax';
};

export type ListGoldTaxPreferencesResponses = {
    /**
     * OK
     */
    200: ListGoldTaxPreferencesRes;
};

export type ListGoldTaxPreferencesResponse = ListGoldTaxPreferencesResponses[keyof ListGoldTaxPreferencesResponses];

export type CreateGoldTaxPreferenceData = {
    /**
     * body
     */
    body: GoldGoldTaxPreferenceReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/gold/tax';
};

export type CreateGoldTaxPreferenceResponses = {
    /**
     * Created
     */
    201: CreateGoldTaxPreferenceRes;
};

export type CreateGoldTaxPreferenceResponse = CreateGoldTaxPreferenceResponses[keyof CreateGoldTaxPreferenceResponses];

export type DeleteGoldTaxPreferenceData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * tax preference id
         */
        id: number;
    };
    query?: never;
    url: '/api/gold/tax/{id}';
};

export type DeleteGoldTaxPreferenceResponses = {
    /**
     * OK
     */
    200: DeleteGoldTaxPreferenceRes;
};

export type DeleteGoldTaxPreferenceResponse = DeleteGoldTaxPreferenceResponses[keyof DeleteGoldTaxPreferenceResponses];

export type UpdateGoldTaxPreferenceData = {
    /**
     * body
     */
    body: GoldGoldTaxPreferenceReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * tax preference id
         */
        id: number;
    };
    query?: never;
    url: '/api/gold/tax/{id}';
};

export type UpdateGoldTaxPreferenceResponses = {
    /**
     * OK
     */
    200: UpdateGoldTaxPreferenceRes;
};

export type UpdateGoldTaxPreferenceResponse = UpdateGoldTaxPreferenceResponses[keyof UpdateGoldTaxPreferenceResponses];

export type DeleteGoldData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * gold id
         */
        id: number;
    };
    query?: never;
    url: '/api/gold/{id}';
};

export type DeleteGoldResponses = {
    /**
     * OK
     */
    200: DeleteGoldRes;
};

export type DeleteGoldResponse = DeleteGoldResponses[keyof DeleteGoldResponses];

export type GetGoldData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * gold id
         */
        id: number;
    };
    query?: never;
    url: '/api/gold/{id}';
};

export type GetGoldResponses = {
    /**
     * OK
     */
    200: GetGoldRes;
};

export type GetGoldResponse = GetGoldResponses[keyof GetGoldResponses];

export type UpdateGoldData = {
    /**
     * body
     */
    body: GoldUpdateGoldReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * gold id
         */
        id: number;
    };
    query?: never;
    url: '/api/gold/{id}';
};

export type UpdateGoldResponses = {
    /**
     * OK
     */
    200: UpdateGoldRes;
};

export type UpdateGoldResponse = UpdateGoldResponses[keyof UpdateGoldResponses];

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    /**
     * OK
     */
    200: HealthHealthRes;
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type PostApiReleaseData = {
    /**
     * body
     */
    body: CreateReleaseReq;
    path?: never;
    query?: never;
    url: '/api/release';
};

export type PostApiReleaseErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type PostApiReleaseError = PostApiReleaseErrors[keyof PostApiReleaseErrors];

export type PostApiReleaseResponses = {
    /**
     * Created
     */
    201: ReleaseRes;
};

export type PostApiReleaseResponse = PostApiReleaseResponses[keyof PostApiReleaseResponses];

export type GetApiReleaseLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/release/latest';
};

export type GetApiReleaseLatestErrors = {
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetApiReleaseLatestError = GetApiReleaseLatestErrors[keyof GetApiReleaseLatestErrors];

export type GetApiReleaseLatestResponses = {
    /**
     * OK
     */
    200: ReleaseRes;
};

export type GetApiReleaseLatestResponse = GetApiReleaseLatestResponses[keyof GetApiReleaseLatestResponses];

export type ListTransactionsData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query: {
        /**
         * wallet id
         */
        wallet_id: number;
        /**
         * include_category
         */
        include_category?: boolean;
        /**
         * start_date
         */
        start_date?: string;
        /**
         * end_date
         */
        end_date?: string;
    };
    url: '/api/transaction';
};

export type ListTransactionsErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type ListTransactionsError = ListTransactionsErrors[keyof ListTransactionsErrors];

export type ListTransactionsResponses = {
    /**
     * OK
     */
    200: Array<DtoTransaction>;
};

export type ListTransactionsResponse = ListTransactionsResponses[keyof ListTransactionsResponses];

export type CreateTransactionData = {
    /**
     * body
     */
    body: CreateTransactionReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/transaction';
};

export type CreateTransactionErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type CreateTransactionError = CreateTransactionErrors[keyof CreateTransactionErrors];

export type CreateTransactionResponses = {
    /**
     * Created
     */
    201: CreateTransactionRes;
};

export type CreateTransactionResponse = CreateTransactionResponses[keyof CreateTransactionResponses];

export type DeleteTransactionData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * transaction id
         */
        id: number;
    };
    query?: never;
    url: '/api/transaction/{id}';
};

export type DeleteTransactionErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type DeleteTransactionError = DeleteTransactionErrors[keyof DeleteTransactionErrors];

export type DeleteTransactionResponses = {
    /**
     * OK
     */
    200: DeleteTransactionRes;
};

export type DeleteTransactionResponse = DeleteTransactionResponses[keyof DeleteTransactionResponses];

export type GetTransactionData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * transaction id
         */
        id: number;
    };
    query?: never;
    url: '/api/transaction/{id}';
};

export type GetTransactionErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetTransactionError = GetTransactionErrors[keyof GetTransactionErrors];

export type GetTransactionResponses = {
    /**
     * OK
     */
    200: GetTransactionRes;
};

export type GetTransactionResponse = GetTransactionResponses[keyof GetTransactionResponses];

export type UpdateTransactionData = {
    /**
     * body
     */
    body: UpdateTransactionReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * transaction id
         */
        id: number;
    };
    query?: never;
    url: '/api/transaction/{id}';
};

export type UpdateTransactionErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type UpdateTransactionError = UpdateTransactionErrors[keyof UpdateTransactionErrors];

export type UpdateTransactionResponses = {
    /**
     * OK
     */
    200: UpdateTransactionRes;
};

export type UpdateTransactionResponse = UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type ListWalletsData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/wallet';
};

export type ListWalletsErrors = {
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type ListWalletsError = ListWalletsErrors[keyof ListWalletsErrors];

export type ListWalletsResponses = {
    /**
     * OK
     */
    200: WalletListWalletsRes;
};

export type ListWalletsResponse = ListWalletsResponses[keyof ListWalletsResponses];

export type CreateWalletData = {
    /**
     * body
     */
    body: WalletCreateWalletReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/wallet';
};

export type CreateWalletErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type CreateWalletError = CreateWalletErrors[keyof CreateWalletErrors];

export type CreateWalletResponses = {
    /**
     * Created
     */
    201: CreateWalletRes;
};

export type CreateWalletResponse = CreateWalletResponses[keyof CreateWalletResponses];

export type DeleteWalletData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * Wallet ID
         */
        id: number;
    };
    query?: never;
    url: '/api/wallet/{id}';
};

export type DeleteWalletErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type DeleteWalletError = DeleteWalletErrors[keyof DeleteWalletErrors];

export type DeleteWalletResponses = {
    /**
     * OK
     */
    200: DeleteWalletRes;
};

export type DeleteWalletResponse = DeleteWalletResponses[keyof DeleteWalletResponses];

export type GetWalletData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * Wallet ID
         */
        id: number;
    };
    query?: never;
    url: '/api/wallet/{id}';
};

export type GetWalletErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type GetWalletError = GetWalletErrors[keyof GetWalletErrors];

export type GetWalletResponses = {
    /**
     * OK
     */
    200: GetWalletRes;
};

export type GetWalletResponse = GetWalletResponses[keyof GetWalletResponses];

export type UpdateWalletData = {
    /**
     * body
     */
    body: WalletUpdateWalletReq;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path: {
        /**
         * Wallet ID
         */
        id: number;
    };
    query?: never;
    url: '/api/wallet/{id}';
};

export type UpdateWalletErrors = {
    /**
     * Bad Request
     */
    400: DtoError;
    /**
     * Unauthorized
     */
    401: DtoError;
    /**
     * Not Found
     */
    404: DtoError;
    /**
     * Internal Server Error
     */
    500: DtoError;
};

export type UpdateWalletError = UpdateWalletErrors[keyof UpdateWalletErrors];

export type UpdateWalletResponses = {
    /**
     * OK
     */
    200: UpdateWalletRes;
};

export type UpdateWalletResponse = UpdateWalletResponses[keyof UpdateWalletResponses];
